### ISSUE TITLE
[Other issue]: Unable to run lasersacn_detector

### ISSUE THREAD

**Issue by Avisheet** [open-rmf/rmf_obstacle_detectors#15]
### Description

I have cloned the rmf_obstacle_detectors and other needed open-rmf repository. I have also successfully ran the demo simulations but while running the below code it's stuck at waiting to configure....
```
ros2 run rmf_obstacle_detector_laserscan laserscan_detector
```
```
[INFO] [1710419018.078797699] [laserscan_obstacle_detector]: Setting parameter range_threshold to 1.000 meters
[INFO] [1710419018.078900384] [laserscan_obstacle_detector]: Setting parameter min_obstacle_size to 0.750 meters
[INFO] [1710419018.078927062] [laserscan_obstacle_detector]: Setting parameter scan_topic_name to lidar/scan
[INFO] [1710419018.078939014] [laserscan_obstacle_detector]: Setting parameter level_name to L1
[INFO] [1710419018.078949124] [laserscan_obstacle_detector]: Setting parameter calibration_sample_count to 10
[INFO] [1710419018.078955505] [laserscan_obstacle_detector]: Waiting to configure...

```
![Screenshot from 2024-03-14 17-53-52](https://github.com/open-rmf/rmf_obstacle_detectors/assets/59338120/f3905591-d9b3-4f69-b434-6cd7d9a0b607)

**Comment by Avisheet** [comment]
@Yadunund can you guide me regarding this ?
So that I can work further in it

**Comment by Yadunund** [comment]
The node is a ROS 2 Lifecycle node.
it might be worth familiarizing yourself with 
* Design: https://design.ros2.org/articles/node_lifecycle.html
* Demos: https://github.com/ros2/demos/tree/rolling/lifecycle

To configure and activate the node
```bash
# to configure
ros2 lifecycle set /laserscan_obstacle_detector configure
```

```bash
# to activate
ros2 lifecycle set /laserscan_obstacle_detector activate
```
I shall close this ticket. If you could open a PR to add this documentation that would be appreciated.
